const students = [{
  StudentId: 'STD1',
  FirstName: 'Gia Khang',
  LastName: 'Trần',
  DateOfBirth: new Date('04/02/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'England',
  Nationality: 'Vietnam',
  JoinDate: new Date('2/4/2018'),
},
{
  StudentId: 'STD2',
  FirstName: 'Ngọc Nhi',
  LastName: 'Trần',
  DateOfBirth: new Date('04/03/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Australia',
  Nationality: 'Laos',
  JoinDate: new Date('3/4/2014'),
},
{
  StudentId: 'STD3',
  FirstName: 'Thị Thùy Như',
  LastName: 'Lâm',
  DateOfBirth: new Date('01/10/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'An Giang',
  Country: 'New Zealand',
  Nationality: 'Campodia',
  JoinDate: new Date('10/1/2018'),
},
{
  StudentId: 'STD4',
  FirstName: 'Quốc Tín',
  LastName: 'Khương',
  DateOfBirth: new Date('01/07/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Vietnam',
  Nationality: 'Thailand',
  JoinDate: new Date('7/1/2014'),
},
{
  StudentId: 'STD5',
  FirstName: 'Trung Tín',
  LastName: 'Trần',
  DateOfBirth: new Date('08/11/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'England',
  Nationality: 'Myanmar',
  JoinDate: new Date('11/8/2014'),
},
{
  StudentId: 'STD6',
  FirstName: 'Khánh Duy',
  LastName: 'Nguyễn',
  DateOfBirth: new Date('3/10/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Australia',
  Nationality: 'Vietnam',
  JoinDate: new Date('10/3/2014'),
},
{
  StudentId: 'STD7',
  FirstName: 'Thị Thảo Nguyên',
  LastName: 'Bùi',
  DateOfBirth: new Date('07/08/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'New Zealand',
  Nationality: 'Laos',
  JoinDate: new Date('8/7/2014'),
},
{
  StudentId: 'STD8',
  FirstName: 'Vũ Thuần',
  LastName: 'Phạm',
  DateOfBirth: new Date('6/10/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Vietnam',
  Nationality: 'Campodia',
  JoinDate: new Date('10/6/2014'),
},
{
  StudentId: 'STD9',
  FirstName: 'Quốc Toản',
  LastName: 'Nguyễn',
  DateOfBirth: new Date('10/12/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'England',
  Nationality: 'Thailand',
  JoinDate: new Date('12/10/2014'),
},
{
  StudentId: 'STD10',
  FirstName: 'Thị Thảo Vi',
  LastName: 'Lê',
  DateOfBirth: new Date('08/08/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Australia',
  Nationality: 'Myanmar',
  JoinDate: new Date('8/8/2014'),
},
{
  StudentId: 'STD11',
  FirstName: 'Chí Tâm',
  LastName: 'Bùi',
  DateOfBirth: new Date('01/07/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'New Zealand',
  Nationality: 'Vietnam',
  JoinDate: new Date('7/1/2014'),
},
{
  StudentId: 'STD12',
  FirstName: 'Thị Mỹ Hương',
  LastName: 'Bùi',
  DateOfBirth: new Date('08/04/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'An Giang',
  Country: 'Vietnam',
  Nationality: 'Laos',
  JoinDate: new Date('4/8/2014'),
},
{
  StudentId: 'STD13',
  FirstName: 'Huỳnh Như',
  LastName: 'Võ',
  DateOfBirth: new Date('09/01/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'England',
  Nationality: 'Campodia',
  JoinDate: new Date('1/9/2014'),
},
{
  StudentId: 'STD14',
  FirstName: 'Ngọc Kiết Tường',
  LastName: 'Phạm',
  DateOfBirth: new Date('06/03/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Australia',
  Nationality: 'Thailand',
  JoinDate: new Date('3/6/2014'),
},
{
  StudentId: 'STD15',
  FirstName: 'Thị Ngọc Huyền',
  LastName: 'Nguyễn',
  DateOfBirth: new Date('04/06/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'New Zealand',
  Nationality: 'Myanmar',
  JoinDate: new Date('6/4/2014'),
},
{
  StudentId: 'STD16',
  FirstName: 'Thị Huỳnh Thư',
  LastName: 'Nguyễn',
  DateOfBirth: new Date('02/06/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Vietnam',
  Nationality: 'Vietnam',
  JoinDate: new Date('6/2/2014'),
},
{
  StudentId: 'STD17',
  FirstName: 'Thị Diễm Trinh',
  LastName: 'Trần',
  DateOfBirth: new Date('05/01/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'An Giang',
  Country: 'England',
  Nationality: 'Laos',
  JoinDate: new Date('1/5/2014'),
},
{
  StudentId: 'STD18',
  FirstName: 'Trần Tùng Dương',
  LastName: 'Phạm',
  DateOfBirth: new Date('02/08/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Australia',
  Nationality: 'Campodia',
  JoinDate: new Date('8/2/2014'),
},
{
  StudentId: 'STD19',
  FirstName: 'Thị Tuyết Xuân',
  LastName: 'Bùi',
  DateOfBirth: new Date('10/02/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'New Zealand',
  Nationality: 'Thailand',
  JoinDate: new Date('2/10/2014'),
},
{
  StudentId: 'STD20',
  FirstName: 'Nguyễn Vinh Hiển',
  LastName: 'Lê',
  DateOfBirth: new Date('2/05/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Vietnam',
  Nationality: 'Myanmar',
  JoinDate: new Date('5/2/2014'),
},
{
  StudentId: 'STD21',
  FirstName: 'Thái Nghi Thường',
  LastName: 'Nguyễn',
  DateOfBirth: new Date('07/05/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'England',
  Nationality: 'Vietnam',
  JoinDate: new Date('5/7/2014'),
},
{
  StudentId: 'STD22',
  FirstName: 'Thị Huỳnh Như',
  LastName: 'Nguyễn',
  DateOfBirth: new Date('03/07/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'An Giang',
  Country: 'Australia',
  Nationality: 'Laos',
  JoinDate: new Date('7/3/2014'),
},
{
  StudentId: 'STD23',
  FirstName: 'Hải Hiền',
  LastName: 'Huỳnh',
  DateOfBirth: new Date('08/07/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'New Zealand',
  Nationality: 'Campodia',
  JoinDate: new Date('7/8/2014'),
},
{
  StudentId: 'STD24',
  FirstName: 'Văn Khởi',
  LastName: 'Nguyễn',
  DateOfBirth: new Date('02/02/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Vietnam',
  Nationality: 'Thailand',
  JoinDate: new Date('2/2/2014'),
},
{
  StudentId: 'STD25',
  FirstName: 'Thuý Đỗ Quyên',
  LastName: 'Nguyễn',
  DateOfBirth: new Date('08/04/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'England',
  Nationality: 'Myanmar',
  JoinDate: new Date('4/8/2014'),
},
{
  StudentId: 'STD26',
  FirstName: 'Văn Ngoãn',
  LastName: 'Bùi',
  DateOfBirth: new Date('09/01/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Australia',
  Nationality: 'Vietnam',
  JoinDate: new Date('1/9/2014'),
},
{
  StudentId: 'STD27',
  FirstName: 'Kim Phi',
  LastName: 'Lê',
  DateOfBirth: new Date('06/03/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'New Zealand',
  Nationality: 'Laos',
  JoinDate: new Date('3/6/2014'),
},
{
  StudentId: 'STD28',
  FirstName: 'Thị Út',
  LastName: 'Lê',
  DateOfBirth: new Date('04/06/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'An Giang',
  Country: 'Vietnam',
  Nationality: 'Campodia',
  JoinDate: new Date('6/4/2014'),
},
{
  StudentId: 'STD29',
  FirstName: 'Hữu Cường',
  LastName: 'Nguyễn',
  DateOfBirth: new Date('12/06/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'England',
  Nationality: 'Thailand',
  JoinDate: new Date('6/12/2014'),
},
{
  StudentId: 'STD30',
  FirstName: 'Thanh Phong',
  LastName: 'Hồ',
  DateOfBirth: new Date('05/01/2004'),
  Gender: 'Female',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'Australia',
  Nationality: 'Myanmar',
  JoinDate: new Date('1/5/2014'),
},
{
  StudentId: 'STD31',
  FirstName: 'Thạnh Trị',
  LastName: 'Bùi',
  DateOfBirth: new Date('12/07/2004'),
  Gender: 'Male',
  Address: '123 some street',
  City: 'Đồng Tháp',
  Country: 'New Zealand',
  Nationality: 'Vietnam',
  JoinDate: new Date('7/12/2014'),
}];

export default students;
